### ISSUE TITLE
[Crawler] 데이터 본문(body)에 이미지 있는 경우

### ISSUE THREAD

**Issue by mataeLee** [catchweak/news-crawler#4]
기사 본문에 이미지 데이터 있는 경우 처리 필요 (형태소 분석 시 이슈)

ex) article id = 82911
웹크롤 타겟 url: https://n.news.naver.com/mnews/article/025/0003366150
기사원문 url: https://www.joongang.co.kr/article/25255622

**Comment by ydj515** [comment]
@mataeLee 
본문에서 이미지나 html 태그가 있다면 빼는게 나을까요?

**Comment by mataeLee** [comment]
@ydj515 
기사 본문의 내용이 어색해지는 것보단 본문에 포함하여 보여주는것이 좋을거같습니다. 
형태소 분석시에 이슈가 되는 부분은 예시 데이터의 경우 사진에 포함된 문구 "사진 유튜브 'FF Channel' 캡처               " 이런식으로 문장이 포함되기 때문입니다.

**Comment by ydj515** [comment]
@mataeLee 
custom image tag를 생성하여 이미지 url을 추가하는 방식으로 진행하였습니다.
![image](https://github.com/user-attachments/assets/1c4d2ec1-aec9-4744-a201-dcb56812131e)

**Comment by ydj515** [comment]
네 그렇게 처리하였습니다
